import mongoose from "mongoose";

const pricingRequestSchema = new mongoose.Schema(
  {
    userId: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: "User", 
      required: true 
    },
    planId: { 
      type: String, 
      enum: ["pro", "enterprise"], 
      required: true 
    },
    billingCycle: { 
      type: String, 
      required: true 
    },
    pricePaid: { 
      type: Number, 
      required: true 
    },
    // Unique Note (e.g., CH-A1B2C) generated by controller
    paymentNote: { 
      type: String, 
      required: true, 
      unique: true 
    },
    // UTR is optional in some cases but unique if provided
    utr: { 
      type: String, 
      default: "N/A" 
    },
    screenshot: { 
      type: String 
    }, // Base64 String for Fast Approval
    couponUsed: { 
      type: String, 
      default: null 
    },
    status: { 
      type: String, 
      enum: ["pending", "approved", "failed"], 
      default: "pending" 
    },
    rejectReason: { 
      type: String 
    },
    activatedAt: { 
      type: Date 
    },
  },
  { timestamps: true }
);

// Indexing for faster admin searches
pricingRequestSchema.index({ paymentNote: 1 });
pricingRequestSchema.index({ utr: 1 });

export default mongoose.model("PricingRequest", pricingRequestSchema);